version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=testuser'
      - 'RABBITMQ_DEFAULT_USER=testuser'
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 16